version: "3"

services:
    mongo:
        image: mongo
        container_name: devRadar_db
        environment:
            MONGO_DATABASE: ${DB_NAME}
            MONGO_USERNAME: ${DB_USERNAME}
            MONGO_PASSWORD: ${DB_PASSWORD}
            MONGO_ROLE: readWrite
        restart: always
        ports:
            - ${DB_PORT}:27017
        volumes:
            - ./database/development/scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh